### ISSUE TITLE
Required MSC2966 `contacts` field is missing from OIDC client registration

### ISSUE THREAD

**Issue by hughns** [vector-im/element-x-ios#1653]
[MSC2966](https://github.com/matrix-org/matrix-spec-proposals/pull/2966) defines how Matrix clients show use dynamic client registration.

The `contacts` field is required but missing from EIX. Note that the RFC7591 doesn't make it mandatory which might be causing some confusion.

Simple fix is to add a value like `["support@element.io"]` which can be overridden like the other OIDC registration values.

**Comment by drott** [comment]
For folks who might come here facing an error ("missing contacts") trying to connect with Element X to their synapse + MAS server, I found that MAS can be told to ignore a missing client contacts field by using the policy engine, compare:
https://matrix-org.github.io/matrix-authentication-service/reference/configuration.html#:~:text=allow_missing_contacts

Example (for a MAS docker config. Adjust path to WASM module, see [documentation](https://matrix-org.github.io/matrix-authentication-service/reference/configuration.html#:~:text=allow_missing_contacts)):
```
policy:
  wasm_module: /usr/local/share/mas-cli/policy.wasm
  client_registration_entrypoint: client_registration/violation
  data:
    client_registration:
      allow_missing_contacts: true
```
